
#[tauri::command]
fn ensure_example_project() -> Result<String, String> {
    // 1. Get executable path to determine where to create the folder
    let exe_path = std::env::current_exe().map_err(|e| e.to_string())?;
    let exe_dir = exe_path.parent().unwrap_or(Path::new("."));
    
    // 2. Define example project path
    let project_path = exe_dir.join("localweaver-example");
    let project_path_str = project_path.to_string_lossy().to_string();

    // 3. Create directory if it doesn't exist
    if !project_path.exists() {
        fs::create_dir_all(&project_path).map_err(|e| e.to_string())?;
    }

    // 4. Check for index.html
    let index_path = project_path.join("index.html");
    if !index_path.exists() {
        let content = r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Examples</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 min-h-screen font-sans">

    <!-- Navbar -->
    <nav class="bg-white shadow-sm">
        <div class="max-w-6xl mx-auto px-4 py-4 flex justify-between items-center">
            <a href="#" class="text-xl font-bold text-blue-600">My Website</a>
            <div class="space-x-4">
                <a href="about.html" class="text-gray-600 hover:text-blue-600">About</a>
                <a href="contact.html" class="text-gray-600 hover:text-blue-600">Contact</a>
            </div>
        </div>
    </nav>

    <!-- Hero Section -->
    <header class="bg-white mt-1">
        <div class="max-w-4xl mx-auto px-4 py-20 text-center">
            <h1 class="text-5xl font-extrabold text-gray-900 mb-6">Build something amazing.</h1>
            <p class="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
                This is a sample project generated by LocalWeaver. You can edit this text, drag in new components, and verify everything works!
            </p>
            <div class="flex justify-center gap-4">
                <button class="px-8 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition">
                    Get Started
                </button>
                <button class="px-8 py-3 bg-gray-200 text-gray-800 rounded-lg font-semibold hover:bg-gray-300 transition">
                    Learn More
                </button>
            </div>
        </div>
    </header>

    <!-- Features Grid -->
    <section class="max-w-6xl mx-auto px-4 py-16">
        <h2 class="text-3xl font-bold text-center mb-12">Why LocalWeaver?</h2>
        <div class="grid md:grid-cols-3 gap-8">
            <div class="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                <div class="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center text-blue-600 mb-4">
                    <i class="fa fa-code border border-dashed p-1"></i>
                </div>
                <h3 class="text-xl font-semibold mb-2">Visual & Code</h3>
                <p class="text-gray-600">Seamlessly switch between drag-and-drop building and raw code editing.</p>
            </div>
            <div class="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                <div class="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center text-purple-600 mb-4">
                    <i class="fa fa-rocket border border-dashed p-1"></i>
                </div>
                <h3 class="text-xl font-semibold mb-2">Local First</h3>
                <p class="text-gray-600">Everything runs locally. No internet connection required for core features.</p>
            </div>
            <div class="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                <div class="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center text-green-600 mb-4">
                    <i class="fa fa-magic border border-dashed p-1"></i>
                </div>
                <h3 class="text-xl font-semibold mb-2">AI Powered</h3>
                <p class="text-gray-600">Use local LLMs to generate content and code snippets on the fly.</p>
            </div>
        </div>
    </section>

</body>
</html>"#;
        fs::write(index_path, content).map_err(|e| e.to_string())?;
    }
    
    // 5. Ensure about.html also exists for link testing
    let about_path = project_path.join("about.html");
    if !about_path.exists() {
        let content = r#"<!DOCTYPE html>
<html>
<head>
    <title>About Us</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="p-10 bg-gray-50">
    <a href="index.html" class="text-blue-500 hover:underline">&larr; Back to Home</a>
    <h1 class="text-4xl font-bold mt-4">About the Team</h1>
    <p class="mt-2 text-gray-600">We are building the future of local web development.</p>
</body>
</html>"#;
         fs::write(about_path, content).map_err(|e| e.to_string())?;
    }

    Ok(project_path_str)
}
